# Generated by Django 2.1.3 on 2018-11-18 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SentimentPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naive_bayes', models.CharField(blank=True, max_length=15, null=True)),
                ('pattern_analyzer', models.CharField(blank=True, max_length=15, null=True)),
                ('rnn_word2vec', models.CharField(blank=True, max_length=15, null=True)),
                ('rnn_gloVe', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user_location', models.CharField(max_length=30)),
                ('created_at', models.CharField(max_length=20)),
                ('sentiment_prediction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='searched_tweets.SentimentPrediction')),
            ],
        ),
        migrations.AddField(
            model_name='searchedtweet',
            name='tweets',
            field=models.ManyToManyField(blank=True, to='searched_tweets.Tweet'),
        ),
    ]
